### ISSUE TITLE
Table of redirects needed for launch

### ISSUE THREAD

**Issue by cazinc** [doi-foundation/doi-website#19]
As part of launch, a list of redirects (from old URLs to new ones, especially for pages that have been replaced/not migrated) is needed. Depending on what the list contains either we (Cazinc) can help set these up in the site, or CRNI may need to do it.

**Comment by ynnig** [comment]
I got paths from Ian at CNRI and put them [here](https://docs.google.com/spreadsheets/d/1e3AHUqRwlixxfz4xRQVDH-jangRUSosRWGGvGXJkqhM/edit#gid=0) for sorting

**Comment by cazinc** [comment]
@JonathanClarkDOIF Ian at CNRI has confirmed that he just needs that table of redirects and they will set things up. 

If you can get us a list of which existing URLs need redirected, and to where, we'll do any final processing on it to make ready for Ian (if necessary) and hand off to him.

**Comment by JonathanClarkDOIF** [comment]
I have updated the list of [www.doi.org](http://www.doi.org/) paths & redirects [here](https://docs.google.com/spreadsheets/d/1e3AHUqRwlixxfz4xRQVDH-jangRUSosRWGGvGXJkqhM/edit?usp=sharing) - both the www redirects tab and the factsheet subset. @ilittle-cnri @ynnig please check what I have done. I have some open questions which I highlighted in yellow. Otherwise I took the view that someone somewhere may have bookmarked any of these links so we do need to redirect them even if the content behind them has been already taken down or not migrated.
