### ISSUE TITLE
Enable redirects on server

### ISSUE THREAD

**Issue by cazinc** [doi-foundation/doi-website#21]
Determine who is responsible for setting up the redirects on the AWS-based server, and get them setup.

**Comment by cazinc** [comment]
@ilittle-cnri we will shortly have a list of redirects that need setup for the new DOI site. Our (Cazinc) understanding is that CNRI would be in charge of actually configuring these, but please confirm if that's not the case, or if you have any questions.

**Comment by ilittle-cnri** [comment]
Yes, once we have a list of redirects from you, we can set that all up.

**Comment by cazinc** [comment]
Great, thanks @ilittle-cnri - will get those to you soon.

**Comment by JonathanClarkDOIF** [comment]
I have updated the list of www.doi.org paths & redirects [here](https://docs.google.com/spreadsheets/d/1e3AHUqRwlixxfz4xRQVDH-jangRUSosRWGGvGXJkqhM/edit?usp=sharing) - both the www redirects tab and the factsheet subset. @ilittle-cnri @ynnig please check what I have done.  I have some open questions which I highlighted in yellow. Otherwise I took the view that someone somewhere may have bookmarked any of these links so we do need to redirect them even if the content behind them has been already taken down or not migrated.

**Comment by cazinc** [comment]
If @ilittle-cnri and @ynnig are OK with these then I don't think we'll need to do anything else - over to CNRI in that case.

**Comment by ynnig** [comment]
Yes, had a scan and these look good Jonathan. 

On 6 Feb 2023, at 09:24, Zach Anthony ***@***.***> wrote:


If @ilittle-cnri <https://github.com/ilittle-cnri> and @ynnig <https://github.com/ynnig> are OK with these then I don't think we'll need to do anything else - over to CNRI in that case.

**Comment by amillercap35** [comment]
@ilittle-cnri the link to the redirect is stored in task #19

**Comment by ilittle-cnri** [comment]
I've configured redirects for everything in the spreadsheet as of Feb 8 at 2:30p EST. You can see this on the staging urls. For example if you go to `https://staging.doi.org/factsheets/DOI_Topics.html`, it should redirect you to the appropriate place.

Take a look and let me know if anything seems amiss.

**Comment by JonathanClarkDOIF** [comment]
Redirects are working
